version: '3.3'

services:
  builder:
    image: jetbrains/teamcity-agent:latest
    environment:
      SERVER_URL: 'http://tc:8111'
    volumes:
      - tc_agent_conf:/data/teamcity_agent/conf
    restart: always
    depends_on:
      - tc
  tc:
    image: jetbrains/teamcity-server:latest
    volumes:
      - tc_data:/data/teamcity_server/datadir
      - tc_logs:/opt/teamcity/logs
    restart: always
  web:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - tc
    volumes:
      - ./nginx/teamcity.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/localhost.crt:/etc/nginx/localhost.crt:ro
      - ./nginx/localhost.key:/etc/nginx/localhost.key:ro
    restart: always
volumes:
  tc_data:
  tc_logs:
  tc_agent_conf: